### ISSUE TITLE
Feature: Possibility to warn users about LightTag instance patching/restart

### ISSUE THREAD

**Issue by SvetlanaVasilyeva** [LightTag/PublicTracker#10]
Is it possible to make broadcast feature a part of setup screen? We have annotation teams in India, Europe and USA, and it's impossible to select a time to upgrade LightTag which is convenient for everyone. What we would like to do is sending broadcast for all users logged in, like "LightTag server will be restarted in 10 mins for maintenance. Please save your work and logout"
Is it possible to implement such feature? As alternative, configurable warning screen at the top could be fine. 

![image](https://user-images.githubusercontent.com/67472995/86037242-0f2a6800-ba0d-11ea-8769-8cadcd6bf9d4.png)

**Comment by talolard** [comment]
Hi Svetlana, 

For annotators, it's very rare (almost never) that we push an update that requires them to log out, a simple refresh is enough in which case their work won't be lost. 

We have an issue in the backlog to notify users when a refresh is needed, we'll try to prioritize it.
