### ISSUE TITLE
Sorting by Task Name doesn't work

### ISSUE THREAD

**Issue by SvetlanaVasilyeva** [LightTag/PublicTracker#11]
Steps: 

Login as manager 
Click Analyze
At the Analyze screen click at Task Name column or arrow. Tasks sorting is not changing. 
Sorting perfectly works for other columns.

**Comment by talolard** [comment]
We're on it

**Comment by talolard** [comment]
Related to https://github.com/talolard/LightTagFE/issues/312

**Comment by talolard** [comment]
Fixed
