### ISSUE TITLE
Issue in task distribution between annotators

### ISSUE THREAD

**Issue by modishajay** [LightTag/PublicTracker#12]
We noticed an issue in the annotation task distribution. For an annotation job with 10 annotation tasks, only 9 were completed. The remaining task appeared shortly, but cannot be traced afterwards. Please refer attached file for details and screenshots.
[Multi-annotator Task Distribution Issue.docx](https://github.com/LightTag/PublicTracker/files/4855271/Multi-annotator.Task.Distribution.Issue.docx)

**Comment by talolard** [comment]
Hi,
Thank you for that detailed explanation it is very helpful 
From the logs, this seems to be working correctly as we can see five documents each annotated by two people.  See the table below. 

When you refresh the screen, you are not getting a new task but rather seeing the one you already annotated, hence why it is grayed out and has annotations. 

We'll work on a flow to make that clearer



|      | id                                   | created_at                       | updated_at                       | status   |   annotator_id | taskset_id                           |
|-----:|:-------------------------------------|:---------------------------------|:---------------------------------|:---------|---------------:|:-------------------------------------|
| 3365 | b4cb4f6f-a155-4865-b2ae-b7bc5a371909 | 2020-06-30 09:46:40.360320-07:00 | 2020-06-30 10:36:50.270252-07:00 | done     |              8 | 475f9567-b3c1-429f-be77-9b6b35fa17cd |
| 3358 | b8760a62-e6fb-4a08-aa38-f876e481e464 | 2020-06-30 10:24:00.151439-07:00 | 2020-06-30 10:27:07.290423-07:00 | done     |              4 | b11931b1-1b13-44b5-aa05-7ed4a5ac2f14 |
| 3359 | 7b3c8675-4239-4071-8784-7a64e6310dfe | 2020-06-30 10:27:07.625813-07:00 | 2020-06-30 10:27:43.014040-07:00 | done     |              4 | 475f9567-b3c1-429f-be77-9b6b35fa17cd |
| 3360 | 33c5c544-ebf8-4d71-8789-c5fc89feb18f | 2020-06-30 10:27:43.483428-07:00 | 2020-06-30 10:28:48.972425-07:00 | done     |              4 | 837e77bc-90e1-4fb2-a3c3-cacc36a7c281 |
| 3364 | bb072bb4-1ebe-46ad-af99-6b3e3a20b125 | 2020-06-30 10:28:49.184994-07:00 | 2020-06-30 10:35:11.398754-07:00 | done     |              4 | e7c6af6e-7a9e-4dda-9a5f-f201bf276312 |
| 3361 | b6033f13-5d6d-429a-8e22-936c0225d2cb | 2020-06-30 10:29:51.315009-07:00 | 2020-06-30 10:31:21.271120-07:00 | done     |              8 | 837e77bc-90e1-4fb2-a3c3-cacc36a7c281 |
| 3362 | d1ee584e-aa0f-4aca-823b-765695a30bc9 | 2020-06-30 10:31:21.589741-07:00 | 2020-06-30 10:32:23.438112-07:00 | done     |              8 | e7c6af6e-7a9e-4dda-9a5f-f201bf276312 |
| 3363 | c59db27a-1cc6-420a-891d-5e2e068a376c | 2020-06-30 10:32:23.695756-07:00 | 2020-06-30 10:33:22.331704-07:00 | done     |              8 | 57800253-f9ed-4c0f-9b49-7a10440bbb4c |
| 3366 | 91bc77cc-d7d4-4ed9-bfc3-f8508e99b9d3 | 2020-06-30 10:33:41.039638-07:00 | 2020-06-30 10:39:21.433499-07:00 | done     |              1 | b11931b1-1b13-44b5-aa05-7ed4a5ac2f14 |
| 3444 | 4efffd02-3a01-4716-87b9-9b34d69d097b | 2020-06-30 21:53:24.994364-07:00 | 2020-06-30 21:53:40.579100-07:00 | done     |             26 | 57800253-f9ed-4c0f-9b49-7a10440bbb4c |
