### ISSUE TITLE
Annotation job created for a few annotators are distributed to "Everyone"

### ISSUE THREAD

**Issue by modishajay** [LightTag/PublicTracker#13]
I created an annotation job from the "Design" tab using "Save New Job" button. Although I entered only two annotators for the job, when I view the job in "Manage" tab, it is assigned to team "Everyone" .
![image](https://user-images.githubusercontent.com/49468307/86627173-b878dd00-bf7c-11ea-9217-6ec91311991d.png)
![image](https://user-images.githubusercontent.com/49468307/86627202-c3337200-bf7c-11ea-903c-75f12549da61.png)

**Comment by talolard** [comment]
Hi,
This duplicates this [internal issue](https://github.com/talolard/LightTagFE/issues/312) which has a ~2 week eta
