### ISSUE TITLE
Critical: Misleading data in LightTag output 

### ISSUE THREAD

**Issue by SvetlanaVasilyeva** [LightTag/PublicTracker#2]
Confirmed by LightTag. Created for tracking the progress. 

We observe the situation where we get LightTag output with incorrect annotations. For example, sometimes, when reviewer selected some label for a clause, it comes in the output with "none" tag. 

![image](https://user-images.githubusercontent.com/67472995/85870855-9e304980-b79b-11ea-9c9d-5378b34ffb52.png)

**Comment by talolard** [comment]
@SvetlanaVasilyeva can you share the exampleId for this

**Comment by talolard** [comment]
A fix for this has landed. 
On your end, we always send all of the annotations made, including ones that were marked as incorrect (even implicitly by changing a tag). 
To get **only** the data that was accepted in review filter on the correct flag

[Notebook showing filtering  on correct only.zip](https://github.com/LightTag/PublicTracker/files/4842924/Notebook.showing.filtering.on.correct.only.zip)
