### ISSUE TITLE
Cache: no correct team members representation after team creation

### ISSUE THREAD

**Issue by SvetlanaVasilyeva** [LightTag/PublicTracker#3]
Steps: 
Create new Team 
Add few annotators to the team 
Save the team (which finalizes team creation)
Screen is refreshed, and we may see newly created team. However, team members column is displayed as empty, which is not quite correct. Admin/manager should re-login so that see list of team members correctly.

**Comment by talolard** [comment]
![newTeam](https://user-images.githubusercontent.com/5352830/86007677-0723f580-ba18-11ea-8045-b16bceeec1ed.gif)
