### ISSUE TITLE
A bug with resolving conflicts during the review process

### ISSUE THREAD

**Issue by EkVasilyeva** [LightTag/PublicTracker#36]
This bug doesn't occur always, but sometimes (we work on prem installation). When we right-click the conflict to resolve it, this is what we get: 
![image](https://user-images.githubusercontent.com/45082166/102930218-0372a800-446a-11eb-8340-cb6f91ff7a5e.png)
We pretty much don't see the conflicting labels when trying to resolve them. If you would be able to resolve this bug, we would really appreciate :)

Sincerely, 
Kate Vasilyeva from Agiloft

**Comment by talolard** [comment]
Hi Kate,
This issue has been resolved and we'll ship it to you in the first week of January. 
Tal
