### ISSUE TITLE
Number of annotations to review is misleading

### ISSUE THREAD

**Issue by SvetlanaVasilyeva** [LightTag/PublicTracker#4]
LightTag has already confirmed the problem, so this issue is created for progress tracking. 

Reviewer may observe misleading number of annotations for some annotated documents. According with information from Tal, suggestions may be counted as annotations in such cases, so it needs to be fixed.

**Comment by talolard** [comment]
Video description of the issue. 
https://www.loom.com/share/c5b2d4e7bd3941908fd2d495c9bfdf12

Fix is to break down the count of annotations to separate humans vs models
