### ISSUE TITLE
Number of assigned annotations to be done is misleading

### ISSUE THREAD

**Issue by SvetlanaVasilyeva** [LightTag/PublicTracker#5]
Steps: 

Create a batch of (say) 10 docs
Create Annotation Job, 2 annotators per doc 
Annotate all documents but one, make it 19/20 
Login as 3rd annotator which is also part of a team annotating test job 
Click "Label" 
Annotation screen with doc for annotation is displayed. Total number of annotation jobs is displayed rather than remaining 1 job. In the described case "10" will be displayed. 
After annotation of the remaining job annotator will be redirected to the next batch, which is correct. 

It is necessary to make display of remaining assigned documents less confusing. It should be refreshed on annotation screen loading, taking into account all annotations which are done by the time when the screen is opened. 

Sample (it's a batch of 70)

![image](https://user-images.githubusercontent.com/67472995/85873448-206e3d00-b79f-11ea-99dd-965afea985c0.png)

**Comment by talolard** [comment]
fixed in f8c704d3
