### ISSUE TITLE
Feature: possibility to edit a Team

### ISSUE THREAD

**Issue by SvetlanaVasilyeva** [LightTag/PublicTracker#6]
I've created several Team so that better distribute document batches and annotators licenses. However, after finalization of this job I've realized that I've forgot to add reviewed to each Team. In LightTag it means that I have to re-do Teams creation, because Team edit is impossible. 
How difficult could be adding possibility to edit Teams? We really need it in some cases, and it could be a nice feature which will be convenient, cover clients' needs and make them happy because of easy Team modifications.

**Comment by talolard** [comment]
![editTeams](https://user-images.githubusercontent.com/5352830/86002743-0fc4fd80-ba11-11ea-8af8-34ab1dabf40b.gif)
