### ISSUE TITLE
Feature: easier access to Team ID

### ISSUE THREAD

**Issue by SvetlanaVasilyeva** [LightTag/PublicTracker#7]
We have an integration with LightTag, which allows us to create annotation jobs in LightTag from our software. However, every time when I create a Team, I need to ask our engineers to get Team ID via API, because I cannot get it by myself. How difficult could be implementation of possibility to see Team ID at a screen which is available for user with manager's permissions?

**Comment by talolard** [comment]
Quick win. Will do

**Comment by talolard** [comment]
![id](https://user-images.githubusercontent.com/5352830/85997045-4e56ba00-ba09-11ea-9f0d-5c2615e8adab.gif)
