### ISSUE TITLE
Critical: display filename along with internal ID at the Review screen

### ISSUE THREAD

**Issue by SvetlanaVasilyeva** [LightTag/PublicTracker#8]
Client's reviewers struggle reviewing annotated documents without possibility to quickly find which filename it is. Only Example IDs are provided. Is there a possibility to display filename as well? Maybe pop-up which appears on moving mouse on an example and click? Something which will not waste screen space, but will allow better navigation between files. 

![image](https://user-images.githubusercontent.com/67472995/85875024-95db0d00-b7a1-11ea-9a8f-49ad179f844b.png)

![image](https://user-images.githubusercontent.com/67472995/85875073-a9867380-b7a1-11ea-9b32-598963f96e45.png)

**Comment by talolard** [comment]
Hi
Would adding an icon with a popup like this be what you're looking for
![dialog](https://user-images.githubusercontent.com/5352830/85942265-889c5a80-b928-11ea-92a3-e8fe4436b4ed.gif)

**Comment by SvetlanaVasilyeva** [comment]
Hi all 

Will it be available for Review in addition? I cannot find this feature at the Review screen for annotation. 

![image](https://user-images.githubusercontent.com/67472995/86049799-c1b7f600-ba20-11ea-87ba-82244127ebc8.png)

**Comment by talolard** [comment]
Yes we can add it to review, I was asking if this would solve the problem for you

**Comment by SvetlanaVasilyeva** [comment]
Yes, it will solve the problem, if filename is displayed. Thanks Tal!

**Comment by talolard** [comment]
![metadata](https://user-images.githubusercontent.com/5352830/89007128-6f604280-d308-11ea-8f60-435f9736fde3.gif)
