### ISSUE TITLE
Critical: possibility to switch between annotation jobs for managers/reviewers

### ISSUE THREAD

**Issue by SvetlanaVasilyeva** [LightTag/PublicTracker#9]
Client requested this change, and it turns out that it may increase customers satisfaction. Can we consider this feature? How long would it take to implement it? 

Annotators probably don't need it, but managers and reviewers would like to be able to switch between batches at the top of annotation screen. Is it possible to introduce this feature? It could be drop-down menu with all permitted unfinished annotation jobs available for the selection. 

![image](https://user-images.githubusercontent.com/67472995/85876261-75ac4d80-b7a3-11ea-95e2-7a32e2e7891f.png)

**Comment by talolard** [comment]
@SvetlanaVasilyeva,  take a look at the design tab. You can see the entire dataset from there in one big list(with search). Is that close to the functionality you’re looking for?

**Comment by talolard** [comment]
@SvetlanaVasilyeva https://www.loom.com/share/a553cfb633144dca92de917fe5f99ad0

**Comment by talolard** [comment]
Hi,
Sorry to say this is going into won't do. 
I'm leaving it open in case other people want it and we will reconsider
Want this feature, give it a +1
